version: 2.1
jobs:

  build:
    environment:
      DOCKER_IMAGE: c4po/harbor-exporter
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_IMAGE:latest .

  push:
    environment:
      DOCKER_IMAGE: c4po/harbor-exporter
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_IMAGE:latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            VERSION=$(cat VERSION)
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$SHORT_GIT_HASH
            docker push $DOCKER_IMAGE:$SHORT_GIT_HASH
            docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$VERSION
            docker push $DOCKER_IMAGE:$VERSION
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
      - push:
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)/
